# Generated by Django 5.1.7 on 2025-03-19 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('opening_date', models.DateTimeField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsules', to='timecapsuleapi.capsulestatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsules', to='timecapsuleapi.capsuletype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecapsules', to='timecapsuleapi.userprofile')),
            ],
        ),
    ]
