# Generated by Django 5.1.7 on 2025-03-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsuleapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('boundary_data', models.JSONField()),
                ('restrictions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='timecapsuleapi.timecapsule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='timecapsuleapi.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='timecapsuleapi.userprofile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='timecapsuleapi.discussionthread')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='timecapsuleapi.timecapsule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_permissions', to='timecapsuleapi.userprofile')),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='timecapsuleapi.permissionlevel')),
            ],
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='timecapsuleapi.storynode')),
            ],
        ),
        migrations.CreateModel(
            name='StoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='timecapsuleapi.storynode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='timecapsuleapi.storynode')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCapsuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='timecapsuleapi.timecapsule')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='timecapsuleapi.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='storynode',
            name='capsule_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_nodes', to='timecapsuleapi.timecapsulecontent'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_predictions', to='timecapsuleapi.userprofile')),
                ('capsule_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='timecapsuleapi.timecapsulecontent')),
                ('verification_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='timecapsuleapi.verificationstatus')),
            ],
        ),
    ]
