# Generated by Django 5.1.7 on 2025-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsuleapi', '0002_contenttype_locationzone_permissionlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecapsule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
